title: Dzenan's protfolio
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: About
      url: /about
    - text: Contact
      url : /contact

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.jpg
author: Dzenan Helic
author_bio: Hello there, my name is Dzenan and I’m a Full Stack developer with more than 3 years of experience in development. I’m most comfortable with stack that includes Angular or React on frontend and Node.js on the backend. Since I have worked on couple of different projects, you can be certain that I will adapt to your workflow as quickly as possible. If you need someone to maintain your legacy project, implement some new features on it or even build something from scratch, I’m your guy so feel free to HIT ME UP. Besides coding in my free time I enjoy gaming, reading about philosophy and history as well as listeting to podcast and trying to learn something new everyday. Active member of student NGO trying to make our world a better place.
author_email: "dzenan.helic@gmail.com"
author_location: Bosnia and Herzegovina
typewrite-text: Welcome to my personal site made using developr a jekyll theme built for developers

# Experiences
author_work_experiences:
            - company_name: Bicom Systems
              company_logo: bicom.png
              company_url: https://www.bicomsystems.com/
              designation: Software Engineer Intern
              description: Worked on PBX System
              visibility: true
            - company_name: Cape Ann Enterprises
              company_logo: cadesign.png
              company_url: https://capeannenterprises.com/
              designation: Drupal & Angular Developer(Intern)
              description: Worked on Drupal 7 project(Active Science)
              visibility: true
            - company_name: Leftor
              company_logo: leftor.jpg
              company_url: https://leftor.com
              designation: PHP(Yii2) Intern
              description: 3 month internship where I worked with Yii2
              visibility: true

# Education
author_education_details:
              - college_logo: fet.png
                college_name: Faculty of Electrical engineering Tuzla
                college_url: http://www.fe.untz.ba/
                college_degree: Automation and Robotics Engineer
                description: Bachelor of Engineering
                visibility: true
              - college_logo: bild.png
                visibility: true
                description: Java Development Training
                college_name: BILD-IT
                college_url: https://mozemo.ba/
                college_degree: Junior Java Developer

# Projects
author_project_details:
              - project_thumbnail: escapeassist.jpg
                project_title: EscapeAssist
                project_description: A Platform for Assisting Escape Room Bussinesses, EscapeAssist uses classic MEAN stack for most of its products.
                project_url: https://escapeassist.com/
                visibility: true
              - project_thumbnail: ericli.webp
                project_title: Eric's Page
                project_description: Personal website using Gastby.io and Sanity.io made with supplied theme and design 
                project_url: https://ericlli.com
                visibility: true
              - project_title: DnD Tools
                project_description: DnD Tools is wiki-like Django web application used as a helper for Dungeons and Dragons players(Only old version is online updates aren't live)
                project_url: http://dndtools.org/
                visibility: true
                project_thumbnail: dndtools.png
              - project_thumbnail: meetingroom.svg
                project_title: Meeting Room 365
                project_description: Meeting Room 365 is Node.js Application For Managing Displays at Your Office. I Worked On Cordova Part Of Application, Where I Had To Create Cordova/Android Pluging For Handling Crashes
                project_url: https://www.meetingroom365.com/
                visibility: true
              - project_thumbnail: watts.jpg
                project_title: Watt's Market
                project_description: Mobile Application Built Using React Native, Application Serves As In Store Inventory Management Working With COMCash POS, Also Had To Develop REST API and CRON Triggered Web Scraping Of Suppliers Data
                visibility: true

# social links
github_username:  dhelic98
linkedin_username: dženan-helić-455aa3136

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
getform_endpoint: 1e51da73-6338-40a0-bf0b-6a19617730bf
formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
